# Generated by Django 3.2.6 on 2021-08-24 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CircunscricaoTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EspecieDeDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cns', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('dia', models.DateField()),
                ('registro_tipo', models.CharField(max_length=1)),
                ('endereco', models.CharField(max_length=100)),
                ('coordenadas_georref', models.BooleanField()),
                ('sobreposicao_de_area', models.CharField(blank=True, default='', max_length=200)),
                ('cns_anterior', models.IntegerField(blank=True, null=True)),
                ('numero_anterior', models.IntegerField(blank=True, null=True)),
                ('encerramento', models.BooleanField()),
                ('bloqueio', models.BooleanField()),
                ('usucapiao', models.CharField(blank=True, default='', max_length=200)),
                ('decisao', models.CharField(blank=True, default='', max_length=200)),
                ('cidade', models.ManyToManyField(to='Imoveis.Cidades')),
                ('circunscricao_territorial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Imoveis.circunscricaoterritorial')),
                ('especie_de_dominio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Imoveis.especiededominio')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaLegalAverbada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ProprietarioPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imoveis.proprietario')),
            ],
        ),
        migrations.CreateModel(
            name='ProprietarioPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imoveis.proprietario')),
            ],
        ),
        migrations.CreateModel(
            name='ImovelUrbano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao_imobiliaria_municipal', models.CharField(blank=True, default='', max_length=20)),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Imoveis.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='ImovelRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sncr', models.CharField(blank=True, default='', max_length=13)),
                ('nirf', models.CharField(blank=True, default='', max_length=100)),
                ('car', models.CharField(blank=True, default='', max_length=100)),
                ('cert_polig', models.CharField(blank=True, default='', max_length=100)),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Imoveis.imovel')),
                ('reserva_legal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Imoveis.reservalegalaverbada')),
            ],
        ),
        migrations.CreateModel(
            name='ImovelPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_direta', models.BooleanField()),
                ('especie_imovel', models.CharField(blank=True, default='', max_length=50)),
                ('legistacao_ou_ato_adm', models.CharField(blank=True, default='', max_length=200)),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Imoveis.imovel')),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='proprietario',
            field=models.ManyToManyField(to='Imoveis.Proprietario'),
        ),
        migrations.AddField(
            model_name='cidades',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Imoveis.estado'),
        ),
        migrations.AddConstraint(
            model_name='proprietariopj',
            constraint=models.UniqueConstraint(fields=('proprietario', 'cnpj'), name='proprietario_pj'),
        ),
        migrations.AddConstraint(
            model_name='proprietariopf',
            constraint=models.UniqueConstraint(fields=('proprietario', 'cpf'), name='proprietario_pf'),
        ),
        migrations.AddConstraint(
            model_name='imovel',
            constraint=models.UniqueConstraint(fields=('cns', 'numero'), name='codigo_imovel'),
        ),
    ]
